spring:
  application:
    name: cognos-portal
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cognos_portal}
    username: ${DB_USERNAME:cognos_admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:default-secret-key-change-in-production-minimum-256-bits}
  expiration: 3600000 # 1 hour in milliseconds

encryption:
  secret: ${ENCRYPTION_KEY:default-encryption-key-change-in-production-32-chars}

polling:
  schedule:
    cron: "0 0 6,18 * * *" # 6 AM and 6 PM daily
  async:
    core-pool-size: 5
    max-pool-size: 20
    queue-capacity: 100

cognos:
  api:
    demo-mode: true  # Set to false when connecting to real Cognos servers

logging:
  level:
    com.pronto.cognosportal: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
